services:
  test_docker_dev:
    pull_policy: never
    container_name: test_docker_dev
    hostname: test_docker_dev
    image: test_dev:latest
    # command: ./mvnw quarkus:dev -Dquarkus.http.host=0.0.0.0    
    restart: unless-stopped
    build:
      context: ./teste_docker
      dockerfile: ../Dockerfile.dev
      target: development
    volumes:
      - ./teste_docker:/app
    ports:
      - "8080:8080"
      - "5005:5005" # Porta de Debug (opcional, mas bom ter)
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://psql:5432/mydatabase
      - QUARKUS_DATASOURCE_USERNAME=${POSTGRES_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      psql:
        condition: service_healthy

  psql:
    container_name: psql
    hostname: psql
    image: postgres:18
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: